---
after: graphqlconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
         jwt: %$Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler
  Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler:
    properties:
      Authenticator: %$Firesphere\GraphQLJWT\Authentication\JWTAuthenticator
---
name: graphqljwt
after:
  - '#coresecurity'
---
Firesphere\GraphQLJWT\Authentication\JWTAuthenticator:
  nbf_time: 0
  nbf_expiration: 3600
  anonymous_allowed: false
